import = [
	"~/.config/alacritty/tempus-themes/tempus_totus.toml"
]

[font]
size = 24.0

[font.normal]
 family = "Spleen 16x32"
#family = "IBM 3270"
#family = "Fairfax Hax HD"
#family = "ProFont"
#family = "Hermit"
#family = "Fira Code"

# abcdefghijklmnopqrstuvwxyz
# ABCDEFGHIJKLMNOPQRSTUVWXYZ
# ?!&:#",{;'<-[(=*)]_>+.}/|%@$~\
# Il1|0Oo
style = "Regular"

[cursor]
style = { shape = "Block", blinking = "Never" }
vi_mode_style = { shape = "Block", blinking = "Never" }
